# -*- mode: ruby -*-
# vim: ft=ruby


# ---- Configuration variables ----

GUI               = false # Enable/Disable GUI
RAM               = 500   # Default memory size in MB

# Network configuration
DOMAIN            = ".example.com"
NETWORK           = " "
NETMASK           = "255.255.255.0"

# Default Virtualbox .box
# See: https://wiki.debian.org/Teams/Cloud/VagrantBaseBoxes
BOX               = "generic/ubuntu1804"

HOSTS = {
  "mysql" => [NETWORK+"118", RAM, GUI, BOX, "mysql.sh"],
  "KotlinAPI" => [NETWORK+"119", RAM, GUI, BOX, "kotlin.sh"]
}

# ---- Vagrant configuration ----

Vagrant.configure(2) do |config|
  HOSTS.each do | (name, cfg) |
    ipaddr, ram, gui, box, provisioning_script = cfg

    config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"

    config.vm.synced_folder "./KotlinAPI", "/home/vagrant/KotlinAPI"

    config.vm.define name do |machine|
      machine.vm.box   = box
      machine.vm.guest = :ubuntu
      machine.vm.provision :shell, path: provisioning_script

      machine.vm.provider "virtualbox" do |vbox|
        vbox.gui    = gui
        vbox.memory = ram
        vbox.name = name
      end

      machine.vm.hostname = name + DOMAIN
      machine.vm.network 'private_network', ip: ipaddr, netmask: NETMASK, name: 'VirtualBox Host-Only Ethernet Adapter #3', adapter:2
    end

  end # HOSTS-each

end
